= Spring Boot 中文参考文档
:author: Zenny Xu
:revnumber: 2.3.3.RELEASE
:keywords: spring-boot
:doctype: book
:icons: font

****
Phillip Webb, Dave Syer, Josh Long, Stéphane Nicoll, Rob Winch, AndyWilkinson, Marcel Overdijk, Christian Dupuis, Sébastien Deleuze, MichaelSimons, Vedran Pavić, Jay Bryant, Madhura Bhave, Eddú Meléndez, ScottFrederick
****

== 目录

== 法律

{revnumber}

Copyright © 2012-2020

本文档的副本可供你自己使用，以及分发给他人，前提是你不得收取任何费用，并且每份副本都须包含本版权声明，无论是以印刷还是电子方式分发。

== 1. Spring Boot 文档

本节会对 Spring Boot 参考文档进行简要描述，以指引文档的其余部分。

=== 1.1. 关于此文档

Spring Boot 参考文档提供如下版本：

- https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/[多页 HTML]
- https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/htmlsingle/[单页 HTML]
- https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/pdf/spring-boot-reference.pdf[PDF]

最新版本的文档副本可以从 https://docs.spring.io/spring-boot/docs/current/reference/[docs.spring.io/spring-boot/docs/current/reference/] 处获取。

本文档的副本可供你自己使用，以及分发给他人，前提是你不得收取任何费用，并且每份副本都须包含本版权声明，无论是以印刷还是电子方式分发。

=== 1.2. 获取帮助

如果你在使用 Spring Boot 是遇到困难，我们愿意提供帮助。

- 尝试 https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/howto.html#howto[“怎么做”的文档] 。它们为最常见的问题提供了解决方案。
- 学习 Spring 基础。Spring Boot 构建于许多其他 Spring 项目之上。可以从 https://spring.io/[spring.io] 网站上查阅到丰富的参考文献。如果你只是刚开始接触 Spring 的萌新，不妨尝试下这些 https://spring.io/guides[指南] 。
- 提问。我们跟踪着 https://stackoverflow.com/[stackoverflow.com] 上标有 https://stackoverflow.com/tags/spring-boot[`spring-boot`] 标签的问题。
- 在 https://github.com/spring-projects/spring-boot/issues[github.com/spring-projects/spring-boot/issues] 上报告关于 Spring Boot 的错误。

NOTE:  Spring  Boot 全部都是开源的，包括文档。如果你发现文档有问题，或者你想改进它们，请 https://github.com/spring-projects/spring-boot/tree/v2.3.3.RELEASE[参与进来] 。

=== 1.3. 第一步

如果你正开始使用 Spring Boot， 或者大致上“ Spring ”，请从以下主题开始：

- 从零开始： https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/getting-started.html#getting-started-introducing-spring-boot[概述] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/getting-started.html#getting-started-system-requirements[要求] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/getting-started.html#getting-started-installing-spring-boot[安装]
- 指导： https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/getting-started.html#getting-started-first-application[上] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/getting-started.html#getting-started-first-application-code[下]
- 实战： https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/getting-started.html#getting-started-first-application-run[上] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/getting-started.html#getting-started-first-application-executable-jar[下]

=== 1.4. 使用 Spring Boot

准备好开始实际使用 Spring Boot 了吗？我们为你提供：

- 构建系统： https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/using-spring-boot.html#using-boot-maven[Maven] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/using-spring-boot.html#using-boot-gradle[Gradle] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/using-spring-boot.html#using-boot-ant[Ant] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/using-spring-boot.html#using-boot-starter[Starters]
- 最佳实践： https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/using-spring-boot.html#using-boot-structuring-your-code[代码结构] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/using-spring-boot.html#using-boot-configuration-classes[@Configuration] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/using-spring-boot.html#using-boot-auto-configuration[@EnableAutoConfiguration] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/using-spring-boot.html#using-boot-spring-beans-and-dependency-injection[Beans 和依赖注入]
- 运行代码： https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/using-spring-boot.html#using-boot-running-from-an-ide[IDE] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/using-spring-boot.html#using-boot-running-as-a-packaged-application[Packaged] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/using-spring-boot.html#using-boot-running-with-the-maven-plugin[Maven] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/using-spring-boot.html#using-boot-running-with-the-gradle-plugin[Gradle]
- 打包应用： https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/using-spring-boot.html#using-boot-packaging-for-production[jars 产品]
- Spring Boot CLI ： https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/spring-boot-cli.html#cli[使用 CLI]

=== 1.5. 了解 Spring Boot 的功能

想要了解更多关于 Spring Boot 核心功能的细节吗？以下内容就是为你准备的：

- 核心功能： https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/spring-boot-features.html#boot-features-spring-application[SpringApplication] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/spring-boot-features.html#boot-features-external-config[外部配置] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/spring-boot-features.html#boot-features-profiles[Profiles] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/spring-boot-features.html#boot-features-logging[日志]
- Web应用： https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/spring-boot-features.html#boot-features-spring-mvc[MVC] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/spring-boot-features.html#boot-features-embedded-container[内嵌容器]
- 数据处理： https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/spring-boot-features.html#boot-features-sql[SQL] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/spring-boot-features.html#boot-features-nosql[NO-SQL]
- 消息： https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/spring-boot-features.html#boot-features-messaging[概述] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/spring-boot-features.html#boot-features-jms[JMS]
- 测试： https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/spring-boot-features.html#boot-features-testing[概述] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/spring-boot-features.html#boot-features-testing-spring-boot-applications[Boot Applications] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/spring-boot-features.html#boot-features-test-utilities[工具]
- 扩展： https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/spring-boot-features.html#boot-features-developing-auto-configuration[自动配置] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/spring-boot-features.html#boot-features-condition-annotations[@Conditions]

=== 1.6. 转入生产

当你准备将自己的 Spring Boot 应用投产时，你可能会对我们提供的 https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/production-ready-features.html#production-ready[这些技巧] 感兴趣：

- 管理终端： https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/production-ready-features.html#production-ready-endpoints[概述]
- 连接选项： https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/production-ready-features.html#production-ready-monitoring[HTTP] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/production-ready-features.html#production-ready-jmx[JMX]
- 监测： https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/production-ready-features.html#production-ready-metrics[指标] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/production-ready-features.html#production-ready-auditing[审计] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/production-ready-features.html#production-ready-http-tracing[HTTP 追踪] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/production-ready-features.html#production-ready-process-monitoring[流程]

=== 1.7. 高级主题

最后，我们还为大佬们提供了几个主题：

- Spring Boot 应用开发： https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/deployment.html#cloud-deployment[云部署] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/deployment.html#deployment-service[操作系统服务]
- 构建工具插件： https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/build-tool-plugins.html#build-tool-plugins-maven-plugin[Maven] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/build-tool-plugins.html#build-tool-plugins-gradle-plugin[Gradle]
- 附录： https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/appendix-application-properties.html#common-application-properties[应用程序属性] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/appendix-configuration-metadata.html#configuration-metadata[配置的元数据] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/appendix-auto-configuration-classes.html#auto-configuration-classes[自动配置类] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/appendix-test-auto-configuration.html#test-auto-configuration[测试自动配置注解] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/appendix-executable-jar-format.html#executable-jar[可执行 Jars] | https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/appendix-dependency-versions.html#dependency-versions[依赖版本]

== 2. 入门

如果你开始使用 Spring Boot ，或者大致上“ Spring ”，请从阅读本节开始。它回答了基本的“什么？”，“怎么？”，“为什么？”的问题。它包括对 Spring Boot 的介绍，以及安装说明。然后，我们将指导你构建第一个 Spring Boot 应用程序，并讨论一些核心原则。

=== 2.1. 介绍 Spring Boot

Spring Boot 帮助你创建独立运行的、生产级的、基于 Spring 的应用程序。我们对 Spring 平台及第三方库进行了整合，以便你就可以以最少的麻烦起步。大多数 Spring Boot 应用程序只需要极少的 Spring 配置。

你可以使用 Spring Boot 来创建 Java 应用程序，并通过使用 `Java-jar` 命令 ，或者更传统的 war 部署来启动。我们还提供了一个命令行工具来运行 “spring 脚本”的。

我们的主要目标是：

- 为所有 Spring 开发提供快捷易用的入门体验。
- 开箱即用，即便需求开始偏离实际，也能迅速另辟蹊径。
- 提供一系列大型项目通用的非功能特性（例如嵌入式服务器、安全性、指标、健康检查、外部化配置）。
- 无需生成代码，无需 XML 配置。

=== 2.2. 系统要求

Spring Boot {revnumber} 需要 https://www.java.com[Java 8] ，并能兼容至 Java 14（含）。除此以外，还需要 https://docs.spring.io/spring/docs/5.2.8.RELEASE/spring-framework-reference/[Spring Framework 5.2.8.RELEASE] 或更高版本的支持。

显式的构建支持已经为以下构建工具提供：

[cols=2*,options="header"]
|===
| 构建工具
| 版本

| Maven | 3.3+
| Gradle | 6 （6.3 或更新）。 5.6.x 也受支持，但不推荐。
|===

==== 2.2.1. Servle 容器

Spring Boot 支持以下内嵌 Servle 容器：

[cols=2*,options="header"]
|===
| 名称
| Servle 版本

| Tomcat 9.0 | 4.0
| Jetty 9.4 | 3.1
| Undertow 2.0 | 4.0
|===

你也可以将 Spring Boot 应用部署到任何与Servlet 3.1+ 兼容的容器中。

=== 2.3. 安装 Spring Boot

Spring Boot 可以和“经典的” Java 开发工具一起使用，也可以安装后作为命令行工具使用。不管怎样，你都需要 https://www.java.com[Java SDK v1.8] 或更高版本。在开始之前，应使用以下命令检查当前安装的 Java ：

[source,shell]
----
$ java -version
----

如果你是 Java 萌新，亦或想体验 Spring Boot ，那么推荐先尝试一下 https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/getting-started.html#getting-started-installing-the-cli[Spring Boot CLI] （命令行界面）。否则，请继续阅读“经典”安装说明。

==== 2.3.1. Java 开发者向安装说明

你可以像任何标准 Java 库一样使用Spring Boot 。使用时，在类路径上引入适当的 `spring-boot-\*.jar` 文件即可。 Spring Boot 不需要任何特殊工具的集成，所以你可以使用任意 IDE （集成开发环境）或文本编辑器 ^※^ 。另外， Spring Boot 应用程序也没有任何特别之处，因此可以像运行其他 Java 程序一样运行和调试 Spring Boot 应用程序。

.※ 译注：关于 IDE 和文本编辑器
[quote]
____
虽然理论上使用文本编辑器是可行的，但对于开发者，特别是初学者而言，使用 IDE 任然是最佳选择，不仅能享受到 IDE 提供的各种便利功能，也能避免诸如乱码（编码格式设置不正确）或文件中含有 BOM 导致编译失败等意想不到的问题。
____

尽管你 __可以__ 复制 Spring  Boot jar包，但是我们通常建议你使用支持依赖管理的构建工具（比如 Maven 或者 Gradle）。

*Maven 安装*

Spring Boot 兼容 Apache Maven 3.3 或更高版本。如果你尚未安装 Maven ，可以按照 https://maven.apache.org[maven.apache.org] 上的说明进行安装。

TIP: 在许多操作系统上，Maven 可以通过包管理器进行安装 ^※^ 。如果你使用 OSX Homebrew，试试 `brew install maven` 命令。 Ubuntu 的用户可以执行 `sudo apt-get install maven` 。而使用 https://chocolatey.org/[Chocolatey] 的 Windows 用户可以通过提权的（管理员）命令提示符执行 `choco install maven` 。

.※ 译注：关于 Maven 版本
[quote]
____
以上这些都是各系统通过包管理器（ homebrew / apt-get / chocolate ）安装 Maven 的命令。需要注意的是这些命令都没有注明安装的版本，通常来说，默认的行为都是安装最新的版本。

这对于个人学习问题不大，但对于工作环境来说，请务必指定统一的安装版本，以免出现在不同的主机上，Maven的工作方式因版本不同不一致的问题。或者，请尝试使用 https://github.com/takari/maven-wrapper[Maven Wrapper]。

最后，在使用各类包管理器进行安装操作时，请务必养成指定版本的良好习惯。
____

Spring Boot 依赖项使用 `org.springframework.boot` 这个 `groupId`。通常情况下，你的 Maven POM 文件继承自 `spring-boot-starter-parent` 项目，并对一个或多个 https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/using-spring-boot.html#using-boot-starter[“Starter”] 声明依赖。此外， Spring Boot 还提供了一个可选的 https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/build-tool-plugins.html#build-tool-plugins-maven-plugin[Maven 插件] 用于创建可执行 jar。

关于 Spring Boot 和 Maven 入门的更多细节可以在 Maven 插件参考指南的 https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/maven-plugin/reference/html/#getting-started[入门部分] 找到。

*Gradle 安装*

Spring Boot 与 Gradle 6（6.3或更高版本）兼容。 Gradle 5.6.x 也受支持，但此支持已废弃，并将在将来的版本中删除。如果你尚未安装 Gradle ，可以按照 https://gradle.org[gradle.org] 上的说明进行安装。

可以通过使用 `org.springframework.boot` 的 `group` 声明 Spring Boot 依赖。通常情况下，你的 Maven POM 文件继承自 `spring-boot-starter-parent` 项目，并对一个或多个 https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/using-spring-boot.html#using-boot-starter[“Starter”] 声明依赖。 此外， Spring Boot 还提供了一个有用的 https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/build-tool-plugins.html#build-tool-plugins-gradle-plugin[Gradle 插件] ，可用于简化依赖声明和创建可执行 jar 。

.Gradle Wrapper
[sidebar]
****
Gradle Wrapper 提供了一种在需要构建项目时“获取” Gradle 的好途径。它只是一个小脚本和库，你可以将它和代码一起提交，以引导构建过程。请查阅 https://docs.gradle.org/current/userguide/gradle_wrapper.html[docs.gradle.org/current/userguide/gradle_wrapper.html] 以获取更详细的信息。
****

关于 Spring Boot 和 Gradle 入门的更多细节可以在 Gradle 插件参考指南的 https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/gradle-plugin/reference/html/#getting-started[入门部分] 找到。

==== 2.3.2. 安装 Spring Boot CLI

Spring Boot CLI （命令行界面）是一个命令行工具，你可以通过它配合 Spring 的使用来迅速构建项目的原型。它可以运行 Groovy 脚本，这意味着你可以使用一种熟悉的，类似 Java 的语法，而不是大量模板代码。

CLI 对于 Spring Boot 开发来说不是必须的，但它绝对是让 Spring 应用程序落地的最快方法。

*手动安装*

你可以从 Spring 软件仓库下载 Spring CLI 的发行版：

- https://repo.spring.io/release/org/springframework/boot/spring-boot-cli/2.3.3.RELEASE/spring-boot-cli-2.3.3.RELEASE-bin.zip[spring-boot-cli-2.3.3.RELEASE-bin.zip]
- https://repo.spring.io/release/org/springframework/boot/spring-boot-cli/2.3.3.RELEASE/spring-boot-cli-2.3.3.RELEASE-bin.tar.gz[spring-boot-cli-2.3.3.RELEASE-bin.tar.gz]

也可以使用最新的 https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-cli/[快照发行版]。

下载后，参照解压文件中 https://raw.githubusercontent.com/spring-projects/spring-boot/v2.3.3.RELEASE/spring-boot-project/spring-boot-cli/src/main/content/INSTALL.txt[INSTALL.txt] 的说明操作即可。总的来说，在 `.zip`文件的 `bin/` 目录下有一个 `spring` 脚本（ Windows 版是 `spring.bat` ）可供使用。或者，你也可以直接使用 `java-jar` 运行 `.jar` 文件（脚本会帮助你确保类路径设置正确）。

*通过 SDKMAN! 安装*

SDKMAN! （软件开发工具包管理器）可用于管理各种二进制 SDK （软件开发工具包）的多个版本，也包括 Groovy 和 Spring Boot CLI 。请从 https://sdkman.io[sdkman.io] 获取 SDKMAN!，然后执行以下命令安装 Spring Boot ：

[source,shell]
----
$ sdk install springboot
$ spring --version
Spring Boot v2.3.3.RELEASE
----

如果你为 CLI 开发功能并希望访问你构建的版本，请使用以下命令：

[source,shell]
----
$ sdk install springboot dev /path/to/spring-boot/spring-boot-cli/target/spring-boot-cli-2.3.3.RELEASE-bin/spring-2.3.3.RELEASE/
$ sdk default springboot dev
$ spring --version
Spring CLI v2.3.3.RELEASE
----

前面的例子安装了一个 `spring` 的本地实例，名为 `dev`。它指向你的目标构建位置，所以每次重新构建Spring Boot 时，`spring` 都是最新的。

你可以运行一下命令来查看：

[source,shell]
----
$ sdk ls springboot

================================================================================
Available Springboot Versions
================================================================================
> + dev
* 2.3.3.RELEASE

================================================================================
+ - local version
* - installed
> - currently in use
================================================================================
----

*通过 OSX Homebrew 安装*

如果你在 Mac 上使用 https://brew.sh[Homebrew]，你可以使用以下命令安装 Spring Boot CLI：

[source,shell]
----
$ brew tap pivotal/tap
$ brew install springboot
----

Homebrew 会将 `spring` 安装在 `/usr/local/bin` 。

NOTE: 如果看不到公式，那么你安装的 brew 很可能已过期。在这种情况下，请运行 `brew update` 更新 brew  后重试。

*通过 MacPorts 安装*

如果你在 Mac 上使用 https://www.macports.org[MacPorts] ，你可以使用以下命令安装 Spring Boot CLI：

[source,shell]
----
$ sudo port install spring-boot-cli
----

*命令行编译*

